### ISSUE TITLE
Audit `Person` model and its attributes

### ISSUE THREAD

**Issue by wei2912** [AY2122S1-CS2103-W14-2/tp#204]
The `Person` model should be audited along with its attributes:

- [x] `Address`
- [x] `CallStatus`
- [x] `CaseNumber`
- [x] `Email`
- [x] `Name`
- [x] `Person`
- [x] `Phone`
- [x] `ShnPeriod`
- [x] `UniquePersonList`

**Comment by jennibearduit** [comment]
May want to consider adding a `getNumFailedCalls` method to `Person` to avoid violation of LoD. Currently I see `person.getCallStatus().getNumFailedCalls()` being used everywhere.

**Comment by frederickpek** [comment]
## Audit Report - `Person` model and its attributes
This audit report will be written in my opinion, comments or changes suggested may or may not be implemented, keeping in mind the deadline for this project is soon.

### Person Model
* Since our code addition to the former AB3, `DuplicatePersonException` and its usages have been deprecated. There are newly written checks in place to ensure no duplicate case numbers before using methods that will throw this exception. It now only serves as an assertion and a testing feature.
* Other components in the Person Model seems fine.

### Attribute abstract class
* On implementing classes: The Attribute class `toString` method simply returns the `value.toString()`. It would perhaps be better for implementing classing that have the form `Attribute<Optional<T>>` to override the `toString` method.
* Other components in the Attribute abstract class seems fine.

### Address attribute
### Address attribute
### Address attribute

**Comment by frederickpek** [comment]
As discussed over zoom, we will close this issue. The regex for `Email` class has to be looked through again as the audit hasnt covered it, task will be assigned to @wei2912.
